version: '3.8'

services:
  api:
    build: .
    container_name: gin-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=debug
      - DB_TYPE=postgres
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-api_user}
      - DB_PASSWORD=${DB_PASSWORD:-api_password}
      - DB_NAME=${DB_NAME:-api}
      - DB_SSLMODE=${DB_SSLMODE:-disable}
      - JWT_SECRET=${JWT_SECRET:-tu_secreto_jwt_super_seguro_aqui}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-24h}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS:-*}
      - CORS_ALLOW_METHODS=${CORS_ALLOW_METHODS:-GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS}
      - CORS_ALLOW_HEADERS=${CORS_ALLOW_HEADERS:-Origin,Content-Length,Content-Type,Authorization}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - api-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  api-network:
    driver: bridge 